# RuboCop configuration for Redmine Move Comments Plugin

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# Redmine plugins often use longer lines due to Rails conventions
Layout/LineLength:
  Max: 120

# Allow empty methods for hooks that might be extended later
Style/EmptyMethod:
  Enabled: false

# Redmine uses older hash syntax in some places
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Documentation is important for plugins
Style/Documentation:
  Enabled: true

# Frozen string literals are good practice
Style/FrozenStringLiteralComment:
  Enabled: true

# Rails specific cops
Rails/ApplicationRecord:
  Enabled: false # Redmine doesn't use ApplicationRecord

Rails/FilePath:
  Enabled: false # Redmine has its own file structure